// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_E1h8E33ExJzDRCjrLe8d7_slmI3p-W0',
    appId: '1:213812007914:web:94b018b5eb78de8391d893',
    messagingSenderId: '213812007914',
    projectId: 'tellbarangay-app',
    authDomain: 'tellbarangay-app.firebaseapp.com',
    storageBucket: 'tellbarangay-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApQLmxNw5-rrILSIWutnzJmKUPZzM5FrA',
    appId: '1:213812007914:android:5bdfa600e9dd633f91d893',
    messagingSenderId: '213812007914',
    projectId: 'tellbarangay-app',
    storageBucket: 'tellbarangay-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1lbGTNPPkn2at1LdB9W1QiNTtbS8WyGE',
    appId: '1:213812007914:ios:0ae440a2abae1d3391d893',
    messagingSenderId: '213812007914',
    projectId: 'tellbarangay-app',
    storageBucket: 'tellbarangay-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1lbGTNPPkn2at1LdB9W1QiNTtbS8WyGE',
    appId: '1:213812007914:ios:0ae440a2abae1d3391d893',
    messagingSenderId: '213812007914',
    projectId: 'tellbarangay-app',
    storageBucket: 'tellbarangay-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_E1h8E33ExJzDRCjrLe8d7_slmI3p-W0',
    appId: '1:213812007914:web:e791d2827d7be9e691d893',
    messagingSenderId: '213812007914',
    projectId: 'tellbarangay-app',
    authDomain: 'tellbarangay-app.firebaseapp.com',
    storageBucket: 'tellbarangay-app.firebasestorage.app',
  );
}
